site_name: Anotações de Estudo
theme: 
  name: material
  logo: img/final.png
  favicon: img/final.ico
  font:
    text: Montserrat
  language: pt-BR
  features:
    - navigation.tracking
    - navigation.instant
    - navigation.tabs
    - navigation.path
    - navigation.indexes
    - navigation.footer
    - search.suggest
    - content.code.copy
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: pink
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: pink
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
plugins:
  - blog
  - tags
  - search
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
  - Assuntos estudados: 
    - index.md
    - Typescript:
      - Utility Types: typescript/utility-types.md
    - Shell:
      - Comandos: shell/comandos.md
      - Teoria: shell/teoria.md
    - Arquitetura:
      - DDD: arquitetura/DDD/intro.md
      - Concorrência: arquitetura/concorrencia/intro.md
      - Design Patterns:
        - Creational:
          - Singleton: design-patterns/creational/singleton.md
